import { BlendModes, EraseModes, Tools } from "../types";
import {
  AppSettings,
  AutoCopyFormats,
  CloseTabBehaviors,
  HotkeySettings,
} from "./types";

/**
 * CONSTANTS & DEFAULTS
 */
export const DEFAULT_HOTKEYS: HotkeySettings = {
  "color.1": { key: "1", ctrl: true },
  "color.2": { key: "2", ctrl: true },
  "color.3": { key: "3", ctrl: true },
  "color.4": { key: "4", ctrl: true },
  "color.5": { key: "5", ctrl: true },
  "color.6": { key: "6", ctrl: true },
  "color.7": { key: "7", ctrl: true },
  "edit.redo": { key: "z", ctrl: true, shift: true },
  "edit.undo": { key: "z", ctrl: true },
  "file.copy": { key: "c", ctrl: true },
  "file.open": { key: "o", ctrl: true },
  "file.save": { key: "s", ctrl: true },
  "nav.centerImage": { key: "c", ctrl: true, alt: true },
  "nav.fitToWindow": { key: "f", ctrl: true, alt: true },
  "nav.ruler": { key: "r", ctrl: true },
  "nav.stretchToFill": { key: "f", ctrl: true },
  "nav.zoomIn": { key: "=", ctrl: true },
  "nav.zoomOut": { key: "-", ctrl: true },
  "tab.close": { key: "w", ctrl: true },
  "tab.new": { key: "t", ctrl: true },
  "tab.next": { key: "tab", ctrl: true },
  "tab.previous": { key: "tab", ctrl: true, shift: true },
  "tool.area": { key: "3" },
  "tool.eraser": { key: "e" },
  "tool.highlighter": { key: "2" },
  "tool.pen": { key: "1" },
};

export const DEFAULT_SETTINGS: AppSettings = {
  autoCopyFormat: AutoCopyFormats.JPEG,
  autoCopyJpegQuality: 0.7,
  autoCopyOnChange: true,
  autoCopyShowToast: false,
  blendMode: BlendModes.NORMAL,
  closeTabBehavior: CloseTabBehaviors.PROMPT,
  closeWindowBehavior: "exit",
  colorPresets: [
    "#FF6B6B",
    "#FF9F43",
    "#FFE066",
    "#6BCB77",
    "#4D96FF",
    "#9B59B6",
    "#FF6B9D",
  ],
  defaultColor: "#FF6B6B",
  defaultAreaBlendMode: BlendModes.MULTIPLY,
  defaultAreaBorderRadius: 0,
  defaultAreaOpacity: 1,
  defaultEraseMode: EraseModes.FULL_STROKE,
  defaultEraserSize: 1,
  defaultHighlighterBlendMode: BlendModes.MULTIPLY,
  defaultHighlighterBorderRadius: 4,
  defaultHighlighterOpacity: 1,
  defaultHighlighterSize: 20,
  defaultPenBlendMode: BlendModes.NORMAL,
  defaultPenOpacity: 1,
  defaultPenSize: 3,
  defaultTool: Tools.PEN,
  hotkeys: DEFAULT_HOTKEYS,
  imageOpenBehavior: "fit",
  manualCopyFormat: AutoCopyFormats.JPEG,
  manualCopyJpegQuality: 0.9,
  selectedPalette: "default",
  showDebugInfo: false,
  theme: "dark",
};
